name: master

on:
  push:
    branches:
    - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Build 🔧
        run: |
          docker build . -t docker.io/erousseau/aws-efs-csi-pv-provisioner:latest
      - name: Push 🚀
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username erousseau --password-stdin
          docker push docker.io/erousseau/aws-efs-csi-pv-provisioner:latest